"""fixed typo in User model

Revision ID: 1b39747f2caa
Revises: d2f1da7a44c2
Create Date: 2018-07-24 19:26:21.177624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b39747f2caa'
down_revision = 'd2f1da7a44c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
