"""adding approved column to jokes table

Revision ID: bc12e3b6a579
Revises: d2f758fd2859
Create Date: 2018-08-22 08:20:59.922998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc12e3b6a579'
down_revision = 'd2f758fd2859'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jokes', sa.Column('approved', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jokes', 'approved')
    # ### end Alembic commands ###
