"""jokes_voted_for column in User model and users_voted column in Joke model using many to many relationship

Revision ID: d2f1da7a44c2
Revises: 3e7923fb5fa9
Create Date: 2018-07-24 19:18:54.975433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2f1da7a44c2'
down_revision = '3e7923fb5fa9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('association',
    sa.Column('users_id', sa.Integer(), nullable=True),
    sa.Column('jokes_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['jokes_id'], ['jokes.id'], ),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association')
    # ### end Alembic commands ###
