"""favorite jokes column

Revision ID: d2f758fd2859
Revises: d5326b3b8dce
Create Date: 2018-08-07 14:11:35.712382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2f758fd2859'
down_revision = 'd5326b3b8dce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
