"""id as unique constraint

Revision ID: ef109473dfb9
Revises: 1b39747f2caa
Create Date: 2018-07-28 15:18:08.533049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef109473dfb9'
down_revision = '1b39747f2caa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'jokes', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'jokes', type_='unique')
    # ### end Alembic commands ###
